from pathlib import Path
from string import Template
ROOT=Path(__file__).resolve().parents[1]
css=(ROOT/'static/broadcast-system.css').read_text()
raw=(ROOT/'templates/broadcast-v2-studio-video-wall.html').read_text().replace('<link rel="stylesheet" href="/static/broadcast-system.css" />','')
ctx={
 'asset_video':'../assets/footage/nasa/earth-observations-sample.mp4','live_label':'Live','timestamp':'18 Oct 2147 / 19:42 UTC-O','segment_label':'Mars Political Desk','headline':'Mars Enters Final Voting Cycle','summary':'A sovereignty referendum across 42 Martian settlement zones could create the first independent off-world republic.','source':'NASA public domain sample','wall_metric_value':'91%','wall_metric_label':'Projected Turnout','lower_role':'Anchor','lower_name':'ANAYA RAO','lower_title':'Senior Anchor • Earth-Orbit Media Ring','lower_location':'Studio','ticker_label':'Headlines','ticker':'MARS TURNOUT PROJECTED AT 91% • EARTH UNION LEGAL REVIEW BEGINS • '
}
html=Template(raw).safe_substitute(ctx)
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Studio Video Wall Approval</title><style>{css}</style><style>body{{margin:0;background:#05070d;color:#f8fafc;font-family:var(--bcast-font);padding:30px}}.wrap{{max-width:1400px;margin:auto}}.head{{display:flex;justify-content:space-between;gap:24px;align-items:end;border-bottom:1px solid var(--bcast-line);padding-bottom:22px;margin-bottom:24px}}.eyebrow{{color:var(--bcast-cyan);font-size:12px;font-weight:950;letter-spacing:.18em;text-transform:uppercase}}h1{{font-family:var(--bcast-condensed);font-size:76px;line-height:.84;text-transform:uppercase;margin:0}}.note{{max-width:620px;color:var(--bcast-muted);line-height:1.45}}.stage{{width:1280px;height:720px;border-radius:24px;overflow:hidden;border:1px solid rgba(255,255,255,.14);background:#03050a}}@media(max-width:1350px){{.stage{{width:960px;height:540px}}.stage>div{{transform:scale(.75);transform-origin:0 0}}}}@media(max-width:980px){{.head{{display:block}}.stage{{width:640px;height:360px}}.stage>div{{transform:scale(.5);transform-origin:0 0}}}}</style></head><body class="bcast-reset"><main class="wrap"><div class="head"><div><div class="eyebrow">Official Primary Style</div><h1>Studio + Video Wall</h1></div><p class="note">Updated check version: removed the fake human silhouette and replaced it with a cleaner anchor desk information card so the layout feels less cheap.</p></div><div class="stage">{html}</div></main></body></html>'''
(ROOT/'static/studio-video-wall-approval.html').write_text(page)
